name: air_puff
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Picture https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.2.3

  # Dart https://github.com/Sky24n/common_utils
  common_utils: 2.1.0

  # Network library
  dio: ^5.3.2

  # Cache
  sp_util: 2.0.3

  # Obtain the current device information https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: ^10.1.0

  # Routing framework https://github.com/theyakka/fluro
  fluro: ^2.0.5

  # Toast https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.3.1

  # State management https://github.com/rrousselGit/provider
  provider: ^6.0.5

  # Notification
  event_bus: 2.0.0

  # Permission
  permission_handler: ^11.0.1

  webview_flutter: ^4.7.0

  google_maps_flutter: ^2.6.0

  map_launcher: ^3.1.0

  geolocator: ^11.0.0

  easy_refresh: ^3.3.5

  flutter_svg: ^2.0.10+1

  fl_chart: ^0.67.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
